import "~/styles/globals.css";
import "sonner/dist/styles.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { ThemeProvider } from "~/components/theme/theme-provider";
import { AppShell } from "~/components/layout/app-shell";
import { ReactQueryProvider } from "~/components/providers/react-query-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={geist.variable} suppressHydrationWarning>
      <body className="min-h-screen bg-neutral-900 text-neutral-900 antialiased dark:bg-neutral-950 dark:text-neutral-100">
        <ReactQueryProvider>
          <ThemeProvider>
            <AppShell>{children}</AppShell>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
